Repository tira-io/tirex-tracker, pull requests merged in 2025-03, with the labels that each got.

#23 CI improvements
  .github/workflows/ci.yml
  README.md
  c/extensions/CMakeLists.txt
  c/include/tirex_tracker.h
  c/src/CMakeLists.txt
  c/src/measure/stats/systemstats_windows.cpp
  jvm/README.md
  jvm/build.gradle.kts
  jvm/library/build.gradle.kts
  jvm/library/src/main/kotlin/io/tira/tirex/tracker/Tracker.kt
  jvm/library/src/test/java/io/tira/tirex/tracker/JavaTrackerTest.java
  python/README.md
  python/pyproject.toml
  python/tirex_tracker/__init__.py
Labels: enhancement

#27 Javadoc
  .github/workflows/ci.yml
  jvm/build.gradle.kts
  jvm/library/build.gradle.kts
Labels: enhancement, java

#26 Java coverage
  .github/workflows/ci.yml
  jvm/library/build.gradle.kts
Labels: enhancement, java

#29 `-o` and `-f"irmetadata"`
  c/examples/03_measure_command/CMakeLists.txt
  c/examples/03_measure_command/config.hpp
  c/examples/03_measure_command/formatters.cpp
  c/examples/03_measure_command/formatters.hpp
  c/examples/03_measure_command/main.cpp
  c/extensions/CMakeLists.txt
  c/extensions/irtracker.cpp
Labels: enhancement, C/C++

#28 Maven Central publishing
  .github/workflows/ci.yml
  jvm/.gitignore
  jvm/build.gradle.kts
  jvm/library/build.gradle.kts
Labels: enhancement, java

#30 Maven Central documentation
  README.md
  jvm/README.md
Labels: documentation, java

#38 Fix PCRE linkage
  c/src/CMakeLists.txt
Labels: dependencies, c/c++

#45 Change default poll interval to 1s
  jvm/library/src/main/kotlin/io/tira/tirex/tracker/Tracker.kt
  python/tirex_tracker/__init__.py
Labels: enhancement

#20 Add PCM support and basic aggregations
  .github/workflows/ci.yml
  README.md
  c/CMakeLists.txt
  c/examples/01_tracking/main.c
  c/examples/03_measure_command/CMakeLists.txt
  c/include/tirex_tracker.h
  c/src/CMakeLists.txt
  c/src/logging.cpp
  c/src/measure/measure.hpp
  c/src/measure/stats/details/macos/ioreport.h
  c/src/measure/stats/details/macos/sysctl.hpp
  c/src/measure/stats/energystats.cpp
  c/src/measure/stats/energystats.hpp
  c/src/measure/stats/gitstats.cpp
  c/src/measure/stats/gitstats.hpp
  c/src/measure/stats/gpustats.hpp
  c/src/measure/stats/nvmlstats.cpp
  c/src/measure/stats/nvmlstats.hpp
  c/src/measure/stats/provider.cpp
  c/src/measure/stats/provider.hpp
  c/src/measure/stats/systemstats.cpp
  c/src/measure/stats/systemstats.hpp
  c/src/measure/stats/systemstats_linux.cpp
  c/src/measure/stats/systemstats_macos.cpp
  c/src/measure/stats/systemstats_windows.cpp
  c/src/measure/utils/sharedlib.hpp
  c/src/measureapi.cpp
  c/src/measureinfo.cpp
Labels: enhancement, c/c++

#71 Fixed non-conformant YAML output
  c/src/measure/stats/systemstats.cpp
  jvm/library/src/main/kotlin/io/tira/tirex/tracker/Tracker.kt
  python/tirex_tracker/__init__.py
Labels: bug, c/c++
